# blog-backend/serverless.yml

service: blog-api-dev

provider:
  name: aws
  runtime: provided.al2   # Go Custom Runtime 사용
  region: ap-northeast-2
  stage: dev
  memorySize: 256
  timeout: 15
  environment:
    DYNAMODB_TABLE: JungyuBlogPosts
  iam:
    role: arn:aws:iam::786382940028:role/JungyuBlogLambdaExecutionRole

package:
  individually: true  # 각 함수를 개별적으로 패키징합니다.

functions:
  getPosts:
    handler: bootstrap       # Custom Runtime은 이 핸들러 대신 'bootstrap' 실행 파일을 찾습니다.
    package:
      artifact: ./artifacts/getPosts.zip
    events:
      - http:
          path: posts
          method: get
          cors:
            origins:
              - 'http://localhost:3000'
              - 'https://blog.jungyu.store'
            headers:
              - Content-Type
              - X-Amz-Date
              - Authorization
              - X-Api-Key
              - X-Amz-Security-Token
            allowCredentials: true

  getPost:
    handler: bootstrap
    package:
      artifact: ./artifacts/getPost.zip
    events:
      - http:
          path: posts/{postId}
          method: get
          cors:
            origins:
              - 'http://localhost:3000'
              - 'https://blog.jungyu.store'
            headers:
              - Content-Type
              - X-Amz-Date
              - Authorization
              - X-Api-Key
              - X-Amz-Security-Token
            allowCredentials: true

  createPost:
    handler: bootstrap
    package:
      artifact: ./artifacts/createPost.zip
    events:
      - http:
          path: posts
          method: post
          cors:
            origins:
              - 'http://localhost:3000'
              - 'https://blog.jungyu.store'
            headers:
              - Content-Type
              - X-Amz-Date
              - Authorization
              - X-Api-Key
              - X-Amz-Security-Token
            allowCredentials: true

  updatePost:
    handler: bootstrap
    package:
      artifact: ./artifacts/updatePost.zip
    events:
      - http:
          path: posts/{postId}
          method: put
          cors:
            origins:
              - 'http://localhost:3000'
              - 'https://blog.jungyu.store'
            headers:
              - Content-Type
              - X-Amz-Date
              - Authorization
              - X-Api-Key
              - X-Amz-Security-Token
            allowCredentials: true

  deletePost:
    handler: bootstrap
    package:
      artifact: ./artifacts/deletePost.zip
    events:
      - http:
          path: posts/{postId}
          method: delete
          cors:
            origins:
              - 'http://localhost:3000'
              - 'https://blog.jungyu.store'
            headers:
              - Content-Type
              - X-Amz-Date
              - Authorization
              - X-Api-Key
              - X-Amz-Security-Token
            allowCredentials: true
